allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.35.3'
  - '@posthog/types@1.390.2'
  - posthog-js@1.391.2
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - esbuild
  - protobufjs
