// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	closeSplashscreen: () => typedError<null, string>(__TAURI_INVOKE("close_splashscreen")),
	getBestMoves: (id: string, engine: string, tab: string, goMode: GoMode, options: EngineOptions) => typedError<[number | null, BestMoves[]] | null, string>(__TAURI_INVOKE("get_best_moves", { id, engine, tab, goMode, options })),
	analyzeGame: (id: string, engine: string, goMode: GoMode, options: AnalysisOptions, uciOptions: EngineOption[]) => typedError<MoveAnalysis[], string>(__TAURI_INVOKE("analyze_game", { id, engine, goMode, options, uciOptions })),
	cancelAnalysis: (id: string) => typedError<null, string>(__TAURI_INVOKE("cancel_analysis", { id })),
	stopEngine: (engine: string, tab: string) => typedError<null, string>(__TAURI_INVOKE("stop_engine", { engine, tab })),
	killEngine: (engine: string, tab: string) => typedError<null, string>(__TAURI_INVOKE("kill_engine", { engine, tab })),
	killEngines: (tab: string) => typedError<null, string>(__TAURI_INVOKE("kill_engines", { tab })),
	getEngineLogs: (engine: string, tab: string) => typedError<EngineLog[], string>(__TAURI_INVOKE("get_engine_logs", { engine, tab })),
	memorySize: () => __TAURI_INVOKE<number>("memory_size"),
	getPuzzle: (file: string, minRating: number, maxRating: number, theme: string | null) => typedError<Puzzle, string>(__TAURI_INVOKE("get_puzzle", { file, minRating, maxRating, theme })),
	searchOpeningName: (query: string) => typedError<OutOpening[], string>(__TAURI_INVOKE("search_opening_name", { query })),
	getOpeningFromFen: (fen: string) => typedError<string, string>(__TAURI_INVOKE("get_opening_from_fen", { fen })),
	getOpeningFromFens: (fens: string[]) => typedError<string, string>(__TAURI_INVOKE("get_opening_from_fens", { fens })),
	getOpeningFromName: (name: string) => typedError<string, string>(__TAURI_INVOKE("get_opening_from_name", { name })),
	getPlayersGameInfo: (file: string, id: number) => typedError<PlayerGameInfo, string>(__TAURI_INVOKE("get_players_game_info", { file, id })),
	getEngineConfig: (path: string) => typedError<EngineConfig, string>(__TAURI_INVOKE("get_engine_config", { path })),
	fileExists: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("file_exists", { path })),
	getFileMetadata: (path: string) => typedError<FileMetadata, string>(__TAURI_INVOKE("get_file_metadata", { path })),
	mergePlayers: (file: string, player1: number, player2: number) => typedError<null, string>(__TAURI_INVOKE("merge_players", { file, player1, player2 })),
	convertPgn: (files: string[], dbPath: string, timestamp: number | null, title: string, description: string | null) => typedError<null, string>(__TAURI_INVOKE("convert_pgn", { files, dbPath, timestamp, title, description })),
	getPlayer: (file: string, id: number) => typedError<{
	id: number,
	name: string | null,
	elo: number | null,
} | null, string>(__TAURI_INVOKE("get_player", { file, id })),
	countPgnGames: (file: string) => typedError<number, string>(__TAURI_INVOKE("count_pgn_games", { file })),
	readGames: (file: string, start: number, end: number) => typedError<string[], string>(__TAURI_INVOKE("read_games", { file, start, end })),
	lexPgn: (pgn: string) => typedError<Token[], string>(__TAURI_INVOKE("lex_pgn", { pgn })),
	isBmi2Compatible: () => __TAURI_INVOKE<boolean>("is_bmi2_compatible"),
	deleteGame: (file: string, n: number) => typedError<null, string>(__TAURI_INVOKE("delete_game", { file, n })),
	deleteDuplicatedGames: (file: string) => typedError<null, string>(__TAURI_INVOKE("delete_duplicated_games", { file })),
	deleteEmptyGames: (file: string) => typedError<null, string>(__TAURI_INVOKE("delete_empty_games", { file })),
	clearGames: () => __TAURI_INVOKE<void>("clear_games"),
	setFileAsExecutable: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_file_as_executable", { path })),
	deleteIndexes: (file: string) => typedError<null, string>(__TAURI_INVOKE("delete_indexes", { file })),
	createIndexes: (file: string) => typedError<null, string>(__TAURI_INVOKE("create_indexes", { file })),
	editDbInfo: (file: string, title: string | null, description: string | null) => typedError<null, string>(__TAURI_INVOKE("edit_db_info", { file, title, description })),
	deleteDbGame: (file: string, gameId: number) => typedError<null, string>(__TAURI_INVOKE("delete_db_game", { file, gameId })),
	writeDbGame: (file: string, gameId: number, pgn: string) => typedError<null, string>(__TAURI_INVOKE("write_db_game", { file, gameId, pgn })),
	deleteDatabase: (file: string) => typedError<null, string>(__TAURI_INVOKE("delete_database", { file })),
	exportToPgn: (file: string, destFile: string) => typedError<null, string>(__TAURI_INVOKE("export_to_pgn", { file, destFile })),
	authenticate: (username: string) => typedError<null, string>(__TAURI_INVOKE("authenticate", { username })),
	writeGame: (filePath: string, n: number, pgn: string) => typedError<null, string>(__TAURI_INVOKE("write_game", { filePath, n, pgn })),
	downloadFile: (id: string, url: string, path: string, token: string | null, finalize: boolean | null, totalSize: number | null) => typedError<null, string>(__TAURI_INVOKE("download_file", { id, url, path, token, finalize, totalSize })),
	getTournaments: (file: string, query: TournamentQuery) => typedError<QueryResponse<Event[]>, string>(__TAURI_INVOKE("get_tournaments", { file, query })),
	getDbInfo: (file: string) => typedError<DatabaseInfo, string>(__TAURI_INVOKE("get_db_info", { file })),
	getGames: (file: string, query: GameQuery) => typedError<QueryResponse<NormalizedGame[]>, string>(__TAURI_INVOKE("get_games", { file, query })),
	searchPosition: (file: string, query: GameQuery, tabId: string) => typedError<[PositionStats[], NormalizedGame[]], string>(__TAURI_INVOKE("search_position", { file, query, tabId })),
	getPlayers: (file: string, query: PlayerQuery) => typedError<QueryResponse<Player[]>, string>(__TAURI_INVOKE("get_players", { file, query })),
	getPuzzleDbInfo: (file: string) => typedError<PuzzleDatabaseInfo, string>(__TAURI_INVOKE("get_puzzle_db_info", { file })),
	getPuzzleThemes: (file: string) => typedError<string[], string>(__TAURI_INVOKE("get_puzzle_themes", { file })),
	getThemesForPuzzle: (file: string, puzzleId: number) => typedError<string[], string>(__TAURI_INVOKE("get_themes_for_puzzle", { file, puzzleId })),
	deletePuzzleDatabase: (file: string) => typedError<null, string>(__TAURI_INVOKE("delete_puzzle_database", { file })),
	startGame: (gameId: string, config: GameConfig) => typedError<GameState, string>(__TAURI_INVOKE("start_game", { gameId, config })),
	getGameState: (gameId: string) => typedError<GameState, string>(__TAURI_INVOKE("get_game_state", { gameId })),
	makeGameMove: (gameId: string, uci: string) => typedError<GameState, string>(__TAURI_INVOKE("make_game_move", { gameId, uci })),
	takeBackGameMove: (gameId: string) => typedError<GameState, string>(__TAURI_INVOKE("take_back_game_move", { gameId })),
	resignGame: (gameId: string, color: string) => typedError<GameState, string>(__TAURI_INVOKE("resign_game", { gameId, color })),
	abortGame: (gameId: string) => typedError<null, string>(__TAURI_INVOKE("abort_game", { gameId })),
	getGameEngineLogs: (gameId: string, color: string) => typedError<EngineLog[], string>(__TAURI_INVOKE("get_game_engine_logs", { gameId, color })),
	preloadReferenceDb: (file: string) => typedError<null, string>(__TAURI_INVOKE("preload_reference_db", { file })),
	getProgress: (id: string) => __TAURI_INVOKE<{
	id: string,
	progress: number | null,
	finished: boolean,
} | null>("get_progress", { id }),
	clearProgress: (id: string) => __TAURI_INVOKE<void>("clear_progress", { id }),
	getSoundServerPort: () => typedError<number, string>(__TAURI_INVOKE("get_sound_server_port")),
};

/** Events */
export const events = {
	bestMovesPayload: makeEvent<BestMovesPayload>("best-moves-payload"),
	clockUpdateEvent: makeEvent<ClockUpdateEvent>("clock-update-event"),
	databaseProgress: makeEvent<DatabaseProgress>("database-progress"),
	gameMoveEvent: makeEvent<GameMoveEvent>("game-move-event"),
	gameOverEvent: makeEvent<GameOverEvent>("game-over-event"),
	progressEvent: makeEvent<ProgressEvent>("progress-event"),
};

/* Types */
export type AnalysisOptions = {
	fen: string,
	moves: string[],
	annotateNovelties: boolean,
	referenceDb: string | null,
	reversed: boolean,
};

export type BestMoves = {
	nodes: number,
	depth: number,
	score: Score,
	uciMoves: string[],
	sanMoves: string[],
	multipv: number,
	nps: number,
};

export type BestMovesPayload = {
	bestLines: BestMoves[],
	engine: string,
	tab: string,
	fen: string,
	moves: string[],
	progress: number | null,
};

export type ClockUpdateEvent = {
	gameId: string,
	whiteTime: number | null,
	blackTime: number | null,
};

export type DatabaseInfo = {
	title: string,
	description: string,
	player_count: number,
	event_count: number,
	game_count: number,
	storage_size: number | null,
	filename: string,
	indexed: boolean,
};

export type DatabaseProgress = {
	id: string,
	progress: number | null,
};

export type DrawReason = "stalemate" | "insufficientMaterial" | "threefoldRepetition" | "fiftyMoveRule" | "agreement";

export type EngineConfig = {
	name: string,
	options: ExportEngineOption[],
};

export type EngineLog = { type: "gui"; value: string } | { type: "engine"; value: string };

export type EngineOption = {
	name: string,
	value: string,
};

export type EngineOptions = {
	fen: string,
	moves: string[],
	extraOptions: EngineOption[],
};

export type Event = {
	id: number,
	name: string | null,
};

export type ExportEngineOption = {
	name: string,
	type: string,
	value: string | null,
	default: string | null,
	min: string | null,
	max: string | null,
	var: string[],
};

export type FileMetadata = {
	last_modified: number,
};

export type GameConfig = {
	white: PlayerConfig,
	black: PlayerConfig,
	whiteTimeControl: TimeControl | null,
	blackTimeControl: TimeControl | null,
	initialFen: string | null,
	initialMoves?: string[],
	openingBook: OpeningBookConfig | null,
};

export type GameEndReason = "checkmate" | "timeout" | "resignation" | "abandonment";

export type GameMove = {
	uci: string,
	san: string,
	fenAfter: string,
	clock: number | null,
	whiteTime: number | null,
	blackTime: number | null,
};

export type GameMoveEvent = {
	gameId: string,
	moves: GameMove[],
	fen: string,
	whiteTime: number | null,
	blackTime: number | null,
};

export type GameOutcome = "Won" | "Drawn" | "Lost";

export type GameOverEvent = {
	gameId: string,
	result: GameResult,
	moves: GameMove[],
};

export type GameQuery = {
	options?: QueryOptions<GameSort> | null,
	player1?: number | null,
	player2?: number | null,
	tournament_id?: number | null,
	start_date?: string | null,
	end_date?: string | null,
	range1?: [number, number] | null,
	range2?: [number, number] | null,
	sides?: Sides | null,
	outcome?: string | null,
	position?: PositionQueryJs | null,
	wanted_result?: string | null,
};

export type GameResult = { type: "whiteWins"; reason: GameEndReason } | { type: "blackWins"; reason: GameEndReason } | { type: "draw"; reason: DrawReason };

export type GameSort = "id" | "date" | "whiteElo" | "blackElo" | "ply_count";

export type GameState = {
	gameId: string,
	status: GameStatus,
	initialFen: string,
	moves: GameMove[],
	currentFen: string,
	ply: number,
	turn: string,
	whiteTime: number | null,
	blackTime: number | null,
	whitePlayer: string,
	blackPlayer: string,
};

export type GameStatus = "playing" | { finished: {
	result: GameResult,
} };

export type GoMode = { t: "PlayersTime"; c: PlayersTime } | { t: "Depth"; c: number } | { t: "Time"; c: number } | { t: "Nodes"; c: number } | { t: "Infinite" };

export type MoveAnalysis = {
	best: BestMoves[],
	novelty: boolean,
	is_sacrifice: boolean,
};

export type NormalizedGame = {
	id: number,
	fen: string,
	event: string,
	event_id: number,
	site: string,
	site_id: number,
	date?: string | null,
	time?: string | null,
	round?: string | null,
	white: string,
	white_id: number,
	white_elo?: number | null,
	black: string,
	black_id: number,
	black_elo?: number | null,
	result: Outcome,
	time_control?: string | null,
	eco?: string | null,
	ply_count?: number | null,
	moves: string,
};

export type OpeningBookConfig = {
	path: string,
	maxPly?: number,
};

export type OutOpening = {
	name: string,
	fen: string,
};

export type Outcome = "1-0" | "0-1" | "1/2-1/2" | "*";

export type Player = {
	id: number,
	name: string | null,
	elo: number | null,
};

export type PlayerConfig = { type: "human"; name: string } | { type: "engine"; name: string; path: string; options?: EngineOption[]; go: GoMode | null };

export type PlayerGameInfo = {
	site_stats_data: SiteStatsData[],
};

export type PlayerQuery = {
	options: QueryOptions<PlayerSort>,
	name?: string | null,
	range?: [number, number] | null,
};

export type PlayerSort = "id" | "name" | "elo";

export type PlayersTime = {
	white: number,
	black: number,
	winc: number,
	binc: number,
};

export type PositionQueryJs = {
	fen: string,
	type_: string,
};

export type PositionStats = {
	move: string,
	white: number,
	draw: number,
	black: number,
};

export type ProgressEvent = {
	id: string,
	progress: number | null,
	finished: boolean,
};

export type ProgressItem = {
	id: string,
	progress: number | null,
	finished: boolean,
};

export type Puzzle = {
	id: number,
	fen: string,
	moves: string,
	rating: number,
	rating_deviation: number,
	popularity: number,
	nb_plays: number,
};

export type PuzzleDatabaseInfo = {
	title: string,
	description: string,
	puzzleCount: number,
	storageSize: number | null,
	path: string,
};

export type QueryOptions<SortT> = {
	skipCount: boolean,
	page?: number | null,
	pageSize?: number | null,
	sort: SortT,
	direction: SortDirection,
};

export type QueryResponse<T> = {
	data: T,
	count: number | null,
};

export type Score = {
	value: ScoreValue,
	/**  The probability of each result (win, draw, loss). */
	wdl: [number, number, number] | null,
};

export type ScoreValue = 
/**  The score in centipawns. */
{ type: "cp"; value: number } | 
/**  Mate coming up in this many moves. Negative value means the engine is getting mated. */
{ type: "mate"; value: number };

export type Sides = "BlackWhite" | "WhiteBlack" | "Any";

export type SiteStatsData = {
	site: string,
	player: string,
	data: StatsData[],
};

export type SortDirection = "asc" | "desc";

export type StatsData = {
	date: string,
	is_player_white: boolean,
	player_elo: number,
	result: GameOutcome,
	time_control: string,
	opening: string,
};

export type TimeControl = {
	initialTime: number,
	increment: number,
};

export type Token = { type: "ParenOpen" } | { type: "ParenClose" } | { type: "Comment"; value: string } | { type: "San"; value: string } | { type: "Header"; value: {
	tag: string,
	value: string,
} } | { type: "Nag"; value: string } | { type: "Outcome"; value: string };

export type TournamentQuery = {
	options: QueryOptions<TournamentSort>,
	name: string | null,
};

export type TournamentSort = "id" | "name";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

